### ISSUE TITLE
Connecting to Google

### ISSUE THREAD

**Issue by andylundqvist** [objective-see/Netiquette#10]
Hello. I am using Netiquette 2.1.1 (and LuLu 2.4.2).

<img width="1435" alt="netiquette" src="https://user-images.githubusercontent.com/55158699/219903627-e475ebc3-55ba-4d0c-87cc-2163d995e9ed.png">

Why do these applications connect to googleusercontent.com?

**Comment by Corzine82** [comment]
I have that same question.  Is there a reason for it?

**Comment by andylundqvist** [comment]
Yeah, it should be a simple to explain. I don’t understand why they would do this and it’s pretty worrying.

**Comment by andylundqvist** [comment]
I am disabling Lulu and all its sibling apps for now. Unless I am blind there is not even a Data Privacy document on the Objective See website (or, as far as I can see, in the different softwares) and this connection to googleusercontent.com (owned by markmonitor.com) can not be GDPR compliant.

**Comment by Corzine82** [comment]
I did the same... it sure would be nice if someone from their team could explain what is going on since this is supposed to be security software??

I only had it activated for a short time but I have no idea what the connection is for.  - I checked too and the remotehost I was connected to was 15.42.188.35.bc.googleusercontent.com (markmonitor.com)

**Comment by andylundqvist** [comment]
@Corzine82 See [this LuLu issue](https://github.com/objective-see/LuLu/issues/531) for an explanation. Disabling crash reporting in the next version should stop this connection.

**Comment by Corzine82** [comment]
Awesome, thanks for the info! 👍🏻
