### ISSUE TITLE
Why does Netiquette establish connection to Github & Google

### ISSUE THREAD

**Issue by artem0** [objective-see/Netiquette#12]
I perceived Netiquette as a monitoring tool that should not establish any kind of connections, kind of better version of netstat and other network monitoring tools. All of sudden, I found  that Netiquette periodically establishes connections to IP address that according to whois are associated with Github and Google:

![photo_2023-06-16 11 16 41 AM](https://github.com/objective-see/Netiquette/assets/9960628/a655fee4-63dd-4b6d-86c8-3e7df5e303bb)

**Comment by idzer0lis** [comment]
Same for me, even after disabling the periodic update checks.
most likely Netiquette is malware, I have no other explanation

**Comment by DaBigBlob** [comment]
How is this still not resolved?

I respect Objective-See, but it is troublesome that an app designed for blocking telemetry (among other things) is sending telemetry without consent. :(
Software that exfiltrates your usage, crashes, or other data from your own machine without advance, opt-in, informed consent is unethical and disrespectful.

@objective-see

**Comment by DaBigBlob** [comment]
in case he really does not bother,
i (we) will just fork objective-see into @objectively-seen and remove ALL telemetry/"crash reporting mechanisms"

**Comment by objective-see** [comment]
Yes, one of the reasons to make this open source is so that anybody can fork/customize :) 

Regardless, I understand you concern(s), and thus I've removed all crash reporting. 
Please manually report any issues/crashes, moving forward, as this was the mechanism that was used to detect bugs/crashes.

The only other networking/connection left in, is a simple update check that reads: `https://objective-see.org/products.json` (which is hosted via GitHub Pages).

```
#define PRODUCT_VERSIONS_URL @"https://objective-see.org/products.json"
productsVersionData = [[NSData alloc] initWithContentsOfURL:[NSURL URLWithString:PRODUCT_VERSIONS_URL]];
```

Note that as this update check is implementing via the client simply reading a remote file, it doesn't send any telemetry / user-data, etc etc... (well, besides an IP address). 

You can also turn this off this update check via Netiquette's preferences:
![image](https://github.com/objective-see/Netiquette/assets/11327812/52530118-bc19-40b3-ba76-25fd854b8b7e).

I will push out a new build of  this "no crash reporting" Netiquette shortly, and also include this new build in new build of LuLu.

**Comment by objective-see** [comment]
Oh, also if "Resolve Names" is enabled, this will generate standard DNS requests to your default DNS server, to resolve the IP addresses of your network connections: 

![image](https://github.com/objective-see/Netiquette/assets/11327812/38e2b99f-fac6-4e1f-a18b-03f35b29b49b).

**Comment by objective-see** [comment]
Crash reporting was removed (previously ...in v2.2: https://github.com/objective-see/Netiquette/commit/206c2acf0bac4e68edc28205685974f0f39a9c9a).
